// Generated by https://quicktype.io

export interface SheetResponse {
	spreadsheetId: string;
	valueRanges: ValueRange[];
}

export interface ValueRange {
	range: string;
	majorDimension: string;
	values: string[][];
}

// Generated by https://quicktype.io

export interface PropertiesResponse {
	sheets: Sheet[];
}

export interface Sheet {
	properties: Properties;
}

export interface Properties {
	title: string;
	gridProperties: GridProperties;
}

export interface GridProperties {
	rowCount: number;
	columnCount: number;
	frozenRowCount?: number;
	frozenColumnCount?: number;
}
