// Generated by https://quicktype.io

export interface MarkersResponse {
	sets: Sets
	timestamp: number
}

export type Sets = {
	[line in MRTLines]: MarkerSet
} & {
	"worldborder.markerset": MarkerSet
	cities: MarkerSet
	old: MarkerSet
	airports: MarkerSet
	"roads.a": MarkerSet
	"roads.b": MarkerSet
	markers: MarkerSet
}

export interface MarkerSet {
	hide: boolean
	circles: Circles
	areas: Areas
	label: string
	markers: Record<string, Marker>
	lines: Record<string, LineType>
	layerprio: number
}

export interface Areas {
	area_1?: Area1
}

export interface Area1 {
	fillcolor: string
	ytop: number
	color: string
	markup: boolean
	x: number[]
	weight: number
	z: number[]
	ybottom: number
	label: string
	opacity: number
	fillopacity: number
}

export type Circles = unknown

export interface LineType {
	color: string
	markup: boolean
	x: number[]
	y: number[]
	weight: number
	z: number[]
	label: string
	opacity: number
}

export interface Marker {
	markup: boolean
	x: number
	icon: string
	y: number
	dim: Dim
	z: number
	label: string
}

export enum Dim {
	The16X16 = "16x16",
	The32X32 = "32x32",
}

type MRTLines =
	// [A] MRT Arctic Line
	| "arctic"
	// [B] MRT Beach Line
	| "beach"
	// [C] MRT Circle Line
	| "circle"
	// [D] MRT Desert Line
	| "desert"
	// [E] MRT Eastern Line
	| "eastern"
	// [F] MRT Forest Line
	| "forest"
	// [H] MRT Savannah Line
	| "savannah"
	// [I] MRT Island Line
	| "island"
	// [J] MRT Jungle Line
	| "jungle"
	// [L] MRT Lakeshore Line
	| "lakeshore"
	// [M] MRT Mesa Line
	| "mesa"
	// [N] MRT Northern Line
	| "northern"
	// [O] MRT Oasis Line
	| "oasis"
	// [P] MRT Plains Line
	| "plains"
	// [R] MRT Rose Line
	| "rose"
	// [S] MRT Southern Line
	| "southern"
	// [T] MRT Taiga Line
	| "taiga"
	// [U] MRT Union Line
	| "union"
	// [V] MRT Valley Line
	| "valley"
	// [W] MRT Western Line
	| "western"
	// [X] MRT Expo Line
	| "expo"
	// [Z] MRT Zephyr Line
	| "zephyr"

export const isMRTLine = (line: string): line is MRTLines => {
	return (
		line === "arctic" ||
		line === "beach" ||
		line === "circle" ||
		line === "desert" ||
		line === "eastern" ||
		line === "forest" ||
		line === "savannah" ||
		line === "island" ||
		line === "jungle" ||
		line === "lakeshore" ||
		line === "mesa" ||
		line === "northern" ||
		line === "oasis" ||
		line === "plains" ||
		line === "rose" ||
		line === "southern" ||
		line === "taiga" ||
		line === "union" ||
		line === "valley" ||
		line === "western" ||
		line === "expo" ||
		line === "zephyr"
	)
}
