extends: stylelint-config-standard
customSyntax: postcss-styled-syntax
overrides:
  - files:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
rules:
  # allow empty sources (e.g. styled.div``)
  no-empty-source: null
  # allow empty blocks (e.g. div {} )
  block-no-empty: null
  # allow unknown selectors (the fresponsive utils can trigger this)
  selector-type-no-unknown: null
