// Generated by https://quicktype.io

export interface MarkersResponse {
	sets: Sets
	timestamp: number
}

export interface Sets {
	southern: MarkerSet
	forest: MarkerSet
	arctic: MarkerSet
	northern: MarkerSet
	zephyr: MarkerSet
	mesa: MarkerSet
	plains: MarkerSet
	"worldborder.markerset": MarkerSet
	expo: MarkerSet
	eastern: MarkerSet
	cities: MarkerSet
	island: MarkerSet
	taiga: MarkerSet
	old: MarkerSet
	savannah: MarkerSet
	airports: MarkerSet
	"roads.a": MarkerSet
	"roads.b": MarkerSet
	lakeshore: MarkerSet
	valley: MarkerSet
	western: MarkerSet
	jungle: MarkerSet
	desert: MarkerSet
	circle: MarkerSet
	union: MarkerSet
	markers: MarkerSet
}

export interface MarkerSet {
	hide: boolean
	circles: Circles
	areas: Areas
	label: string
	markers: Record<string, Marker>
	lines: Record<string, LineType>
}

export interface Areas {
	area_1?: Area1
}

export interface Area1 {
	color: string
	markup: boolean
	x: number[]
	weight: number
	z: number[]
	label: string
	opacity: number
}

export type Circles = unknown

export interface LineType {
	color: string
	markup: boolean
	x: number[]
	y: number[]
	weight: number
	z: number[]
	label: string
	opacity: number
}

export interface Marker {
	markup: boolean
	x: number
	icon: string
	y: number
	dim: Dim
	z: number
	label: string
}

export enum Dim {
	The16X16 = "16x16",
	The32X32 = "32x32",
}

type MRTLines =
	| "southern"
	| "forest"
	| "arctic"
	| "northern"
	| "zephyr"
	| "mesa"
	| "plains"
	| "expo"
	| "eastern"
	| "island"
	| "taiga"
	| "savannah"
	| "lakeshore"
	| "valley"
	| "western"
	| "jungle"
	| "desert"
	| "circle"
	| "union"

export const isMRTLine = (line: string): line is MRTLines => {
	return (
		line === "southern" ||
		line === "forest" ||
		line === "arctic" ||
		line === "northern" ||
		line === "zephyr" ||
		line === "mesa" ||
		line === "plains" ||
		line === "expo" ||
		line === "eastern" ||
		line === "island" ||
		line === "taiga" ||
		line === "savannah" ||
		line === "lakeshore" ||
		line === "valley" ||
		line === "western" ||
		line === "jungle" ||
		line === "desert" ||
		line === "circle" ||
		line === "union"
	)
}
