// Generated by https://quicktype.io

export interface Dynmap {
  sets: Sets
  timestamp: number
}

export interface Sets {
  southern: Southern
  forest: Forest
  arctic: Arctic
  northern: Northern
  zephyr: Desert
  mesa: Desert
  plains: Desert
  "worldborder.markerset": WorldborderMarkerset
  expo: Desert
  eastern: Eastern
  cities: Airports
  island: Island
  taiga: Desert
  old: Old
  savannah: Savannah
  airports: Airports
  "roads.a": Roads
  "roads.b": Roads
  lakeshore: Lakeshore
  valley: Valley
  western: Western
  jungle: Jungle
  desert: Desert
  circle: Circle
  markers: SetsMarkers
}

export interface Airports {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: CirclesClass
  layerprio: number
}

export interface CirclesClass {}

export interface Marker {
  markup: boolean
  x: number
  icon: string
  y: number
  dim: Dim
  z: number
  label: string
}

export enum Dim {
  The16X16 = "16x16",
  The32X32 = "32x32",
}

export interface Arctic {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: ArcticLines
  layerprio: number
}

export interface ArcticLines {
  "ax2-1": PuneHedgehog
  ax: PuneHedgehog
  arctic: PuneHedgehog
  ax2: PuneHedgehog
}

export interface PuneHedgehog {
  color: string
  markup: boolean
  x: number[]
  y: number[]
  weight: number
  z: number[]
  label: string
  opacity: number
}

export interface Circle {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: CircleLines
  layerprio: number
}

export interface CircleLines {
  circle: PuneHedgehog
}

export interface Desert {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: { [key: string]: PuneHedgehog }
  layerprio: number
}

export interface Eastern {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: EasternLines
  layerprio: number
}

export interface EasternLines {
  enz: PuneHedgehog
  es2: PuneHedgehog
  en: PuneHedgehog
  "esx-2": PuneHedgehog
  "esx-1": PuneHedgehog
  es: PuneHedgehog
}

export interface Forest {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: ForestLines
  layerprio: number
}

export interface ForestLines {
  forest: PuneHedgehog
  fx: PuneHedgehog
}

export interface Island {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: IslandLines
  layerprio: number
}

export interface IslandLines {
  ix2: PuneHedgehog
  island: PuneHedgehog
  ix: PuneHedgehog
}

export interface Jungle {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: JungleLines
  layerprio: number
}

export interface JungleLines {
  jn: PuneHedgehog
  js1: PuneHedgehog
  js: PuneHedgehog
}

export interface Lakeshore {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: LakeshoreLines
  layerprio: number
}

export interface LakeshoreLines {
  lex1: PuneHedgehog
  le: PuneHedgehog
  lw: PuneHedgehog
  lwx: PuneHedgehog
}

export interface SetsMarkers {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: MarkersMarkers
  lines: CirclesClass
  layerprio: number
}

export interface MarkersMarkers {
  _spawn_new: Marker
}

export interface Northern {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: NorthernLines
  layerprio: number
}

export interface NorthernLines {
  nex: PuneHedgehog
  ne: PuneHedgehog
  nw: PuneHedgehog
  nwx: PuneHedgehog
}

export interface Old {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: CirclesClass
  lines: CirclesClass
  layerprio: number
}

export interface Roads {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: CirclesClass
  lines: { [key: string]: PuneHedgehog }
  layerprio: number
}

export interface Savannah {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: SavannahLines
  layerprio: number
}

export interface SavannahLines {
  h: PuneHedgehog
}

export interface Southern {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: SouthernLines
  layerprio: number
}

export interface SouthernLines {
  se: PuneHedgehog
  sw: PuneHedgehog
  swx: PuneHedgehog
}

export interface Valley {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: ValleyLines
  layerprio: number
}

export interface ValleyLines {
  vx: PuneHedgehog
  valley: PuneHedgehog
}

export interface Western {
  hide: boolean
  circles: CirclesClass
  areas: CirclesClass
  label: string
  markers: { [key: string]: Marker }
  lines: WesternLines
  layerprio: number
}

export interface WesternLines {
  wnx: PuneHedgehog
  wn: PuneHedgehog
  "western-north": PuneHedgehog
}

export interface WorldborderMarkerset {
  hide: boolean
  circles: CirclesClass
  areas: WorldborderMarkersetAreas
  label: string
  markers: CirclesClass
  lines: CirclesClass
  layerprio: number
}

export interface WorldborderMarkersetAreas {
  worldborder_new: WorldborderNew
}

export interface WorldborderNew {
  fillcolor: string
  ytop: number
  color: string
  markup: boolean
  x: number[]
  weight: number
  z: number[]
  ybottom: number
  label: string
  opacity: number
  fillopacity: number
}
