// Generated by https://quicktype.io

export interface Member {
  Rank: Rank
  Username: number | string
  "Became Member": string
  "Last Promoted": string
  "Supporter?": Supporter
  "Conductor/Mod Candidacy": ConductorModCandidacy
  "Temporary Usernames": string
  "Former Usernames": string
  "Standard rank": Rank
  Notes: string
  "Trustee Promotion Date": string
}

export enum ConductorModCandidacy {
  DeclinedForMod = "Declined for Mod",
  DeclinedForModNotVetoedForConductorF = "Declined for Mod, Not Vetoed for Conductor (F)",
  DeclinedForModNotVetoedForModF = "Declined for Mod, Not Vetoed for Mod (F)",
  Empty = "",
  NotVetoedForConductorF = "Not Vetoed for Conductor (F)",
  NotVetoedForModC = "Not Vetoed for Mod (C)",
  NotVetoedForModF = "Not Vetoed for Mod (F)",
  NotVetoedForModFC = "Not Vetoed for Mod (F, C)",
  NotVetoedForModFDeclinedForMod = "Not Vetoed for Mod (F), Declined for Mod",
  VetoedForConductorF = "Vetoed for Conductor (F)",
  VetoedForConductorFC = "Vetoed for Conductor (F, C)",
  VetoedForModF = "Vetoed for Mod (F)",
  VetoedForModFNotVetoedForConductorF = "Vetoed for Mod (F), Not Vetoed for Conductor (F)",
}

export enum Rank {
  Administrator = "Administrator",
  Citizen = "Citizen",
  Conductor = "Conductor",
  Councillor = "Councillor",
  Empty = "",
  Governor = "Governor",
  Mayor = "Mayor",
  Member = "Member",
  Moderator = "Moderator",
  Owner = "Owner",
  Premier = "Premier",
  RankCouncillor = "councillor",
  Senator = "Senator",
  Trustee = "Trustee",
}

export enum Supporter {
  Empty = "",
  Yes = "Yes",
}
