// Generated by https://quicktype.io

export interface WorldInfo {
  currentcount: number
  hasStorm: boolean
  players: Player[]
  isThundering: boolean
  confighash: number
  servertime: number
  updates: Update[]
  timestamp: number
}

export interface Player {
  world: string
  armor: number
  name: string
  x: number
  y: number
  health: number
  z: number
  sort: number
  type: string
  account: string
}

export interface Update {
  type: Type
  name?: string
  timestamp: number
  msg?: string
  x?: number
  y?: number
  z?: number
  id?: string
  label?: string
  icon?: string
  set?: string
  markup?: boolean
  desc?: string
  dim?: string
  minzoom?: number
  maxzoom?: number
  ctype?: string
}

export enum Type {
  Component = "component",
  Tile = "tile",
}
