import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { Providers } from "./providers"
import { dehydrate, HydrationBoundary } from "@tanstack/react-query"
import { styled } from "restyle"
import { MapServer } from "components/Map/Server"
import { getQueryClient } from "trpc/server"

import "./global.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const queryClient = getQueryClient()

	return (
		<html lang="en">
			<body
				className={inter.className}
				style={{ fontWeight: 300 }}
				// for theme cookie
				suppressHydrationWarning
			>
				<Providers>
					<HydrationBoundary state={dehydrate(queryClient)}>
						<Application>
							<MapServer />
							{children}
						</Application>
					</HydrationBoundary>
				</Providers>
			</body>
		</html>
	)
}

const Application = styled("div", {
	width: "100dvw",
	height: "100dvh",
	overflow: "clip",
	display: "grid",
	gridTemplateColumns: "1fr 1fr 1fr",
	placeItems: "start stretch",
})
