import { styled } from "@linaria/react"
import {
	HydrationBoundary,
	QueryClient,
	dehydrate,
} from "@tanstack/react-query"
import AppGrid from "./AppGrid"
import MinecraftMap from "./components/Map/MapServer"
import { RoutingProvider } from "./components/RoutingContext"
import { getArticleContent } from "./components/Wiki/getArticleContent"
import "./global.css"
import { findPath } from "./pathing"
import { compressedPlaces } from "./utils/compressedPlaces"
import { findClosestPlace } from "./utils/search"

export const metadata = {
	title: "Create Next App!!!",
	description: "Generated by create next app",
}

export default async function MainPage({
	searchParams,
}: {
	searchParams: { [key: string]: string | string[] | undefined }
}) {
	const queryClient = new QueryClient()

	// prefetch wiki article
	const fromID = Array.isArray(searchParams.from)
		? searchParams.from[0]
		: searchParams.from
	const toID = Array.isArray(searchParams.to)
		? searchParams.to[0]
		: searchParams.to
	const relevantPlace = findClosestPlace(toID, compressedPlaces)
	const name = relevantPlace?.name || relevantPlace?.id || toID
	if (!fromID)
		await queryClient.prefetchQuery({
			queryKey: ["wiki-article", name],
			queryFn: async () => {
				return name ? getArticleContent(name) : null
			},
		})

	// prefetch route
	await queryClient.prefetchQuery({
		queryKey: ["find-path", fromID, toID],
		queryFn: () => findPath(fromID, toID),
	})

	// prefetch search params
	await queryClient.prefetchQuery({
		queryKey: ["search-params"],
		queryFn: () => searchParams,
	})

	return (
		<HydrationBoundary state={dehydrate(queryClient)}>
			<RoutingProvider>
				<Application>
					<MinecraftMap />
					<AppGrid places={compressedPlaces} />
				</Application>
			</RoutingProvider>
		</HydrationBoundary>
	)
}

const Application = styled.div`
	width: 100dvw;
	height: 100dvh;
	overflow: clip;
	display: grid;
	grid-template-columns: 1fr 1fr 1fr;
	place-items: start stretch;
`
