export interface Routes {
  [key: string]: Route
}

export interface Route {
  /**
   * should match the database key
   */
  uniqueId: string
  /**
   * the name of this route, if it has one
   */
  name: null | string
  /**
   * a short description of the route, if it has one
   */
  description: null | string
  /**
   * what type of route is this?
   */
  type: RouteMode
  /**
   * if available, the route number
   */
  number: null | string
  /**
   * the provider of this route
   */
  provider: string
  /**
   * if true, this route may be overwritten automatically
   */
  autoGenerated: boolean
  /**
   * the locations that this route passes through and at which gate or platform
   */
  locations: RouteLocations
  /**
   * number of gates
   */
  numGates: number | null
}

export type RouteMode =
  | "flight"
  | "seaplane"
  | "heli"
  | "MRT"
  | "walk"
  | "spawnWarp"

export interface RouteLocations {
  [key: string]: string
}
