// Generated by https://quicktype.io

export interface SheetResponse {
  spreadsheetId: string
  valueRanges: ValueRange[]
}

export interface ValueRange {
  range: string
  majorDimension: string
  values: string[][]
}
