// Generated by https://quicktype.io

export interface ExtractResponse {
  batchcomplete: string
  query: ExtractQuery
  limits: Limits
}

export interface Limits {
  extracts: number
}

export interface ExtractQuery {
  pages: Pages
}

export type Pages = Record<string, Found | NotFound>

export interface NotFound {
  ns: number
  title: string
  missing: string
}

export interface Found {
  pageid: number
  ns: number
  title: string
  extract: string
}
