name: Code Checks
on: pull_request
jobs:
  # Deploy_Preview:
  #   env:
  #     CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  #     CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Install and Build
  #       run: |
  #         npm install
  #         npm run build
  #     - name: Deploy
  #       uses: shlinkio/deploy-preview-action@v1.0.1
  #       with:
  #         branch: gh-pages # The branch from where the GitHub Pages are served (defaults to preview-env)
  #         folder: public # The folder where the artifacts to publish are (defaults to the project root)
  Automatically_Format:
    # Check if the PR is not from a fork
    # only run if not authored by dependabot
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.author != 'dependabot[bot]'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Install Modules
        run: npm install
      - name: format
        run: npm run format
        continue-on-error: true
      - name: Check for changes and commit
        run: |
          if git diff --exit-code; then
            echo "No changes detected"
            exit 0
          fi
          git config --global user.name 'AutoFormatter'
          git config --global user.email 'formatter@example.com'
          git remote set-url origin https://x-access-token:${{ secrets.FORMATTER_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automatically Formatted"
          git push
          exit 1
  Check_Linting:
    # Check if the PR is not from a fork
    # only run if not authored by dependabot
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.author != 'dependabot[bot]'
    runs-on: self-hosted
    needs: Automatically_Format
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - uses: sibiraj-s/action-eslint@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          eslint-args: "--ignore-path=.gitignore --quiet"
          extensions: "js,jsx,ts,tsx"
          annotations: true
  Type_Checking:
    # Check if the PR is not from a fork
    # only run if not authored by dependabot
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.author != 'dependabot[bot]'
    runs-on: self-hosted
    needs: Automatically_Format
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Check types
        run: npx tsc --noEmit
  Verify_Formatting:
    # Check if the PR is not from a fork
    # only run if not authored by dependabot
    if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.author != 'dependabot[bot]'
    runs-on: self-hosted
    needs: Automatically_Format
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci
      - name: Format
        run: npm run format
        continue-on-error: true
      - name: Check formatting
        run: |
          if [ -n "$(git diff --name-only --exit-code)" ]; then
            echo "There are changes to format in the following files:"
            git diff --name-only
            exit 1
          fi
          exit 0
