# github action that runs every day at
#   UTC - 07:00 AM
#   MST - 12:00 AM
#   MDT - 01:00 AM
# and can also be triggered manually
name: Importer
on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
jobs:
  import:
    runs-on: ubuntu-latest
    env:
      CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Modules
        run: |
          npm install
      - name: Import to Database
        run: |
          npm run import
      - name: Upload database artifact
        uses: actions/upload-artifact@v2
        with:
          name: database
          path: packages/database-importer/database.json
      - name: Send Heartbeat
        run: |
          curl -X GET https://betteruptime.com/api/v1/heartbeat/WZxUmQ6m6wYxkwCSWPPz1tAD
