import AutogeneratedTags from "assets/images/pwa/AutogeneratedTags"
import { graphql, useStaticQuery } from "gatsby"

interface SEOProps {
  title?: string
  description?: string
  pathname?: string
  creator?: string
  image?: string
}

export default function Seo({
  title,
  description,
  pathname,
  creator = "",
  image,
}: SEOProps) {
  const {
    title: defaultTitle,
    description: defaultDescription,
    image: defaultImage,
    siteUrl,
  } = useSiteMetadata() ?? {}

  const seo = {
    title: title ?? defaultTitle ?? "Untitled",
    description: description ?? defaultDescription ?? "No description",
    image: image ?? defaultImage ?? "",
    url: siteUrl && pathname ? `${siteUrl}/${pathname}` : "",
    creator,
  }

  return (
    <>
      {/* favicon */}
      <link rel="icon" type="image/x-icon" href="/favicon.ico" />

      {/* basic head elements */}
      <title>{seo.title}</title>
      <meta name="description" content={seo.description} />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, minimal-ui"
      />

      {/* google fonts (Inter and Material Symbols Outlined) */}
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
        rel="stylesheet"
      />

      {/* twitter seo */}
      <meta name="twitter:card" content="summary" />
      <meta name="twitter:creator" content={seo.creator} />
      <meta name="twitter:title" content={seo.title} />
      <meta name="twitter:description" content={seo.description} />
      <meta name="twitter:image" content={seo.image} />

      {/* og seo */}
      <meta property="og:title" content={seo.title} />
      <meta property="og:description" content={seo.description} />
      <meta property="og:image" content={seo.image} />
      <meta property="og:url" content={seo.url} />
      <meta property="og:type" content="website" />

      <AutogeneratedTags />
    </>
  )
}

export const useSiteMetadata = () => {
  const data: Queries.MetadataQuery = useStaticQuery(graphql`
    query Metadata {
      site {
        siteMetadata {
          title
          description
          image
          siteUrl
        }
      }
    }
  `)

  return data.site?.siteMetadata
}
